#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-hoe-seattlerb
Version  : 1.3.5
Release  : 6
URL      : https://rubygems.org/downloads/hoe-seattlerb-1.3.5.gem
Source0  : https://rubygems.org/downloads/hoe-seattlerb-1.3.5.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
= hoe-seattlerb
home :: https://github.com/seattlerb/hoe-seattlerb
rdoc :: http://seattlerb.rubyforge.org/hoe-seattlerb

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n hoe-seattlerb-1.3.5
gem spec %{SOURCE0} -l --ruby > rubygem-hoe-seattlerb.gemspec

%build
gem build rubygem-hoe-seattlerb.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
hoe-seattlerb-1.3.5.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/hoe-seattlerb-1.3.5
rake --trace test TESTOPTS="-v"
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/hoe-seattlerb-1.3.5.gem
/usr/lib64/ruby/gems/2.3.0/gems/hoe-seattlerb-1.3.5/.autotest
/usr/lib64/ruby/gems/2.3.0/gems/hoe-seattlerb-1.3.5/History.txt
/usr/lib64/ruby/gems/2.3.0/gems/hoe-seattlerb-1.3.5/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/hoe-seattlerb-1.3.5/README.txt
/usr/lib64/ruby/gems/2.3.0/gems/hoe-seattlerb-1.3.5/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/hoe-seattlerb-1.3.5/lib/hoe/email.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-seattlerb-1.3.5/lib/hoe/history.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-seattlerb-1.3.5/lib/hoe/perforce.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-seattlerb-1.3.5/lib/hoe/seattlerb.rb
/usr/lib64/ruby/gems/2.3.0/specifications/hoe-seattlerb-1.3.5.gemspec
